#include <iostream>
using namespace std;


int main() {
    string DNA = "GTCCAGTCACCCTGCTACGGGCGTTCTATCCTACTAACGCAACTGTTAGTCATAGTTCTAACGAATGTCCCGTGCCACTTGTGGGCCTAGTGCGGCTATTTGCTCGAAACACAATTACCTCAAAGGAGGTCTTTAGGATGAGATCTCCCGGCAGTCACTAAAGCGGATTACAATGGCAGACAGCTCTATGTCGTGAAGGGTGCAGTATTCCGTTTCAAAACGGTCATGGCGAGGTTATTAGCATAGGAACTCGAATACTAGGTAGCGTATAATAGGCCTTACGGCTTTGTCCCACAGTTTGACTAGGGTCGTGTTATGTACGCATCGTCGGTCTGGGGATGAACTATGGCAATGCGATGAACAAGGGCTGTTAGCGCAACACACCGTAGTTGGTATTCATTCACTCAAGGAGTACCGCACACGCGCGCCAAACATTGCCCACGGCTATTCCCTTAGCATATCTAGATGGATCCTTTTCTAACGCCCACTGTAGCACCTACCCTATAGCTTGTGACGTGGTTCGCATTGGCGAGTAGAAGTGTGCACTTGTCCCTTGTAGTTTAGGTCATGGTATATACTCTTTACACTGATTATTGCAATACGCATAGAACGCGGATCATATCAGACAATTTCAGTGGCAGAGAAACAAGAGGTTTCCCCGGTTAACCTACTAAATGGTGAAGGACACACTACGCATCCTTGAAGCCTCTCTGCTAGGGGAGTGCTAGGTGGAGGCTTCAATCCGTGTGGCACGATTGAACGTCCCGGAATACAGATCGTGATTCTTTGGGCCTTTGAAGGGAGGCTTAGCCAGATCAATTCGACTCCGTCAATTTGACTGCTTACGTCCTAATGCTTTGATAATATACTAGCGTTCGCACCCTAGAAAGAGGCACGAGACACCT";

    string RNA;
    string replacer;
    
    for (int i =0; i < DNA.length(); i++) {
        string replacer;
        
        replacer = DNA[i];
        if (replacer == "T") {
            RNA = RNA + "U";
            
        }
        else {
            RNA = RNA + DNA[i];

        }
        

    }
    cout << RNA;
   }


